### ISSUE TITLE
Incoming Calls fixes

### ISSUE THREAD

**Issue by rawmain** [rawmain/flyme-l861#1]
Log : 

```
12-26` 15:45:05.567 17100 17100 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method matchesCallFilter(Landroid/os/Bundle;)[Z in class Landroid/app/INotificationManager; or its super classes (declaration of 'android.app.INotificationManager' appears in /system/framework/framework.jar)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at android.app.NotificationManager.matchesCallFilter(NotificationManager.java:347)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.server.telecom.Call.shouldRingForContact(Call.java:2309)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.server.telecom.Call.isCallShouldRingForContact(Call.java:2314)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.server.telecom.CallAudioManager.updateAudioStreamAndMode(CallAudioManager.java:741)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.server.telecom.CallAudioManager.updateAudioStreamAndMode(CallAudioManager.java:733)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.server.telecom.CallAudioManager.setIsRinging(CallAudioManager.java:571)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.server.telecom.Ringer.startRingingOrCallWaiting(Ringer.java:248)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.server.telecom.Ringer.updateRinging(Ringer.java:215)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.server.telecom.Ringer.onCallAdded(Ringer.java:130)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.server.telecom.CallsManager.addCall(CallsManager.java:1799)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.server.telecom.CallsManager.onSuccessfulIncomingCall(CallsManager.java:370)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.server.telecom.Call.onCallFilteringComplete(Call.java:1038)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.server.telecom.Call.-wrap1(Call.java)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.server.telecom.Call$4.run(Call.java:1011)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.server.SystemServer.run(SystemServer.java:306)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.server.SystemServer.main(SystemServer.java:178)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-26 15:45:05.567 17100 17100 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Later I'm testing following fix for file framework.jar.out/smali/android/app/INotificationManager.smali : 

Line 242
```
-.method public abstract matchesCallFilter(Landroid/os/Bundle;)Z
+.method public abstract matchesCallFilter(Landroid/os/Bundle;)[Z
```

**Comment by rawmain** [comment]
Above fix doesn't work.

There isn't instead any FC/reboot, applying 'blank method' workaround for matchesCallFilter on file framework.jar.out/smali/android/app/NotificationManager.smali : 

Line 1009
```
.method public matchesCallFilter(Landroid/os/Bundle;)Z
    .locals 1

    .prologue
    const/4 v0, 0x0

    return v0
.end method
```

However InCall sound notifications become quite imperceptible.

Still working on it.

**Comment by rawmain** [comment]
Built new OTA package (20171227) that uses the following patch : 

https://github.com/rawmain/flyme-l861/commit/aebe7daebdaee83d18ff2d347f2fe316d60dc53b

- Vibration now is working for incoming calls
- Volume still low for ringtone alerts
